### ISSUE TITLE
Issue with prepare npy files

### ISSUE THREAD

**Issue by Tejuwi** [VisualComputingInstitute/3d-semantic-segmentation#1]
Thanks for providing the code for public. I am trying to create npy file for training. I am getting the following error. can you please help me to fix it?

(3DSeg) C:\Users\Documents\3DDeep_LIDAR\tools>python prepare_s3dis.py --input_dir Dataset --output_dir OUT
Program was launched with the following arguments:
~ input_dir      Dataset
~ output_dir     OUT

  0%|                                                                                                                                                             | 0/272 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "prepare_s3dis.py", line 75, in <module>
    main(params)
  File "prepare_s3dis.py", line 57, in main
    out_filename = elements[-3] + '_' + elements[-2] + '.npy'  # Area_1_hallway_1.npy
IndexError: list index out of range

**Comment by louis-mouline** [comment]
@pradAI How did you fix this problem ?

**Solution** : if you are using Windows OS, you have to change every ".split('/')" to ".split('\\')"
